(in-package :cl-ascii-art)

(defun border (&key (stream *standard-output*) (width 60) (height 40) (hborder 1) (vborder 1) (chars ".")
                 (even t))
  (iter (for row from 0 to height)
    (iter (for col from 0 to width)
      (princ
       (if (or (and (< col hborder))
               (< row vborder)
               (> col (- width hborder))
               (> row (- height vborder)))
           (if (zerop (mod col 2))
               (random-elt chars)
               #\space)
           #\space)
       stream))
    (terpri stream))))

(defparameter *earth* "🌍🌎🌏")
(defparameter *heart-bike* "☙♡♥❣❤❥❦❧🎔💑💓💔💕💖💗💘💙💚💛💜💝💞💟😍😻🚲🚴🚵🚲🚴🚵🚲🚴🚵🚲🚴🚵🚲🚴🚵🚲🚴🚵🚲🚴🚵🚲🚴🚵🚲🚴🚵🚲🚴🚵🚲🚴🚵🚲🚴🚵")
